In [4]:
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img

In [3]:
datagen = ImageDataGenerator(
    rotation_range=40,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

In [12]:
img = load_img('./1.jpg')
x = img_to_array(img) # of shape (3,150,150)
print(x)

[[[ 36.  41.  37.]
  [ 37.  42.  38.]
  [ 38.  42.  41.]
  ...
  [200. 198. 160.]
  [200. 198. 159.]
  [203. 201. 162.]]

 [[ 38.  43.  39.]
  [ 39.  44.  40.]
  [ 39.  43.  42.]
  ...
  [205. 203. 165.]
  [203. 201. 162.]
  [204. 202. 163.]]

 [[ 41.  46.  42.]
  [ 41.  46.  42.]
  [ 41.  45.  44.]
  ...
  [203. 200. 165.]
  [199. 197. 159.]
  [197. 195. 157.]]

 ...

 [[ 33.  31.  32.]
  [ 30.  28.  29.]
  [ 26.  24.  25.]
  ...
  [ 41.  28.  20.]
  [ 37.  24.  16.]
  [ 61.  51.  42.]]

 [[ 34.  32.  33.]
  [ 32.  30.  31.]
  [ 27.  25.  26.]
  ...
  [ 44.  31.  23.]
  [ 37.  24.  16.]
  [ 65.  55.  46.]]

 [[ 30.  28.  29.]
  [ 28.  26.  27.]
  [ 26.  24.  25.]
  ...
  [ 61.  48.  40.]
  [ 39.  26.  18.]
  [ 38.  28.  19.]]]


In [13]:
x = x.reshape((1,) + x.shape) # reshaping it into (1,3,150,150) and also run only 1 time
print(x.shape)

(1, 281, 300, 3)


In [16]:
i = 0
# the save_to_dir= path is given in the same directory of the file
for batch in datagen.flow(x, batch_size=1, save_to_dir='preview', save_prefix='cat',save_format='jpeg'):
    i+=1
    if i>20:
        break

## Loading all the images from a folder

In [1]:
import cv2
import os

def load_images_from_folder(folder):
    images = []
    for filename in os.listdir(folder):
        img = cv2.imread(os.path.join(folder,filename))
        if img is not None:
#             cv2.imshow('image',img)
            images.append(img)
    cv2.waitKey(0) 
  
    #closing all open windows 
    cv2.destroyAllWindows()
    return images

print(len(load_images_from_folder('preview')))

21
