In [1]:
import time
from collections import namedtuple

In [2]:
import numpy as np
import tensorflow as tf

In [5]:
with open ('book.txt' , 'r',encoding="utf8") as f:
    text = f.read()
vocab = set (text)
vocab_to_int = {c: i for i, c in enumerate(vocab)}
int_to_vocab = dict(enumerate(vocab))
encoded = np.array([vocab_to_int[c] for c in text], dtype=np.int32)



In [6]:
text[:100]

'The Project Gutenberg eBook of Pride and Prejudice, by Jane Austen\n\nThis eBook is for the use of any'

In [7]:
encoded[:100]

array([49, 60, 66,  3, 64, 12, 80, 38, 66, 24,  2,  3, 55, 20,  2, 66,  6,
       48, 66, 12, 42,  3, 66, 91, 80, 80, 13,  3, 80, 68,  3, 64, 12, 89,
       39, 66,  3, 69,  6, 39,  3, 64, 12, 66, 38, 20, 39, 89, 24, 66,  7,
        3, 48, 26,  3, 45, 69,  6, 66,  3, 65, 20, 28,  2, 66,  6, 23, 23,
       49, 60, 89, 28,  3, 66, 91, 80, 80, 13,  3, 89, 28,  3, 68, 80, 12,
        3,  2, 60, 66,  3, 20, 28, 66,  3, 80, 68,  3, 69,  6, 26])

In [8]:
len(vocab)

92

In [9]:
def get_batches (arr, n_seqs, n_steps):
    # Get the batch size and the number of batches
    batch_size = n_seqs * n_steps
    n_batches = len(arr)/batch_size
    # Keep enough chars to make full batches
    arr=arr[:int(n_batches * batch_size)]
    # reshape into n_seqs rows
    arr = arr.reshape((n_seqs,-1))
    for n in range (0, arr.shape[1], n_steps):
        #Features
        x=arr[:,n:n+n_steps]
        #Targets, shifted by one
        y=np.zeros_like(x)
        y[: , :-1], y[: , -1] = x[ : , 1:], x[:,0]
        yield x,y
    print('x\n', x[:10, :10])
    print('\ny\n', y[:10, :10])

In [10]:
gen=get_batches(encoded,3,2)

In [11]:
next(gen)

(array([[49, 60],
        [69,  2],
        [26,  3]]),
 array([[60, 49],
        [ 2, 69],
        [ 3, 26]]))